# Generated by Django 4.2.7 on 2023-12-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/'),
        ),
    ]
