# Generated by Django 4.2.7 on 2023-12-03 11:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('FICTION', 'FICTION'), ('APP', 'APP'), ('SECURITY', 'SECURITY'), ('TECH', 'TECH'), ('AI', 'AI'), ('BLOG', 'BLOG')], default='BLOG', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogimage/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
